---
- name: Install MySQL
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: present

- name: Start MySQL service
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Create MySQL user
  shell: |
    sudo mysql -e "CREATE USER IF NOT EXISTS 'devops'@'%' IDENTIFIED BY 'password';"
    sudo mysql -e "CREATE USER IF NOT EXISTS 'devops'@'localhost' IDENTIFIED BY 'password';"
    sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'devops'@'%';"
    sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'devops'@'localhost';"
    sudo mysql -e "FLUSH PRIVILEGES;"
  args:
    executable: /bin/bash

- name: Copy SQL initialization file
  copy:
    src: "{{ lookup('env', 'WORKSPACE') }}/sql/init.sql"
    dest: /tmp/init.sql

- name: Initialize database
  shell: sudo mysql < /tmp/init.sql
  args:
    executable: /bin/bash
