---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Apache and PHP
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - unzip
    state: present

- name: Enable Apache service
  systemd:
    name: apache2
    state: started
    enabled: yes
